name: labextension

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.13']
        jupyterlab-version: ['4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install dependencies
        run: python -m pip install 'jupyterlab~=${{ matrix.jupyterlab-version }}.0'
      - name: Build the extension
        run: |
          jlpm
          jlpm run eslint:check
          python -m pip install .
          jupyter labextension list

          jupyter labextension list 2>&1 | grep -ie "dask-labextension.*OK"
          python -m jupyterlab.browser_check
