name: python

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install
        shell: bash -l {0}
        run: python -m pip install '.[test]'

      - name: Run Tests
        shell: bash -l {0}
        run: python -m pytest dask_labextension
